FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS dotnet

COPY . /src/
RUN mkdir -p /home/site/wwwroot
RUN cd /src/CompressImagesFunction && dotnet publish CompressImagesFunction.csproj --output /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/dotnet:2.0

ENV AzureWebJobsScriptRoot=/home/site/wwwroot
COPY --from=dotnet ["/home/site/wwwroot", "/home/site/wwwroot"]
