// <auto-generated/>

namespace Auth.Model
{
    public class Account
    {
        public string url { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public string login { get; set; }
        public string avatar_url { get; set; }
    }
}
