// <auto-generated/>

namespace Auth.Model
{
    public class Branch
    {
        public string name { get; set; }
        public bool @protected { get; set; }
        public string protection_url { get; set; }
    }
}
