// <auto-generated/>

using System;
using System.Collections.Generic;

namespace MarketplaceSyncFunction
{
    public class Plan
    {
        public string url { get; set; }
        public string accounts_url { get; set; }
        public int id { get; set; }
        public int number { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int monthly_price_in_cents { get; set; }
        public int yearly_price_in_cents { get; set; }
        public string price_model { get; set; }
        public bool has_free_trial { get; set; }
        public object unit_name { get; set; }
        public string state { get; set; }
        public List<string> bullets { get; set; }
    }

    public class MarketplacePurchase
    {
        public string billing_cycle { get; set; }
        public int unit_count { get; set; }
        public bool on_free_trial { get; set; }
        public object free_trial_ends_on { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? next_billing_date { get; set; }
        public Plan plan { get; set; }
    }

    public class Account
    {
        public string url { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public string login { get; set; }
        public object email { get; set; }
        public object marketplace_pending_change { get; set; }
        public MarketplacePurchase marketplace_purchase { get; set; }
    }

    public class PlanData
    {
        public Account[] value { get; set; }
    }
}
